### ISSUE TITLE
Crash on Server Start

### ISSUE THREAD

**Issue by suerion** [Lemon4ik6484/MossMod#1]
Hey, i had an Issue on my Server. The server crash with this issue on startup

```
[19:11:00] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'moss' at 'dev.lemonnik.moss.Moomoss'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) ~[fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.16.5.jar:?]
        at net.minecraft.server.Main.main(Main.java:111) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.5.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.21.1-loader.0.16.5-launcher.1.0.1.jar:1.0.1]
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/item/v1/FabricItemSettings
        at dev.lemonnik.moss.Moomoss.onInitialize(Moomoss.java:29) ~[moomoss-1.0.0.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.5.jar:?]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.item.v1.FabricItemSettings
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.5.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at dev.lemonnik.moss.Moomoss.onInitialize(Moomoss.java:29) ~[moomoss-1.0.0.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.5.jar:?]
        ... 7 more
```

Fabric 1.21.1 with 0.16.5
https://mclo.gs/qkyhDrP

**Comment by Lemonnik6484** [comment]
Hello, thank you for report!

I can recreate your issue and will release update soon that will fix this issue

**Comment by suerion** [comment]
> Hello, thank you for report!
> 
> I can recreate your issue and will release update soon that will fix this issue

@Lemon4ik6484 hey, thanks a lot :) thougth this would be a nice mob :) hope i could use it in my big modpack ;)

**Comment by Lemonnik6484** [comment]
Btw, the update will be ready in 1-3 days, it's just incompatible with the new fabric API version so it should be easy to fix

**Comment by suerion** [comment]
Okey, thanks :)

**Comment by Lemonnik6484** [comment]
Hello, I updated mod to version 1.0.1! It should fix your issue, if issue still exists re-open this issue or create the new one
(Already availible on Modrinth, might take a while to get approved on CurseForge)

**Comment by suerion** [comment]
> Hello, I updated mod to version 1.0.1! It should fix your issue, if issue still exists re-open this issue or create the new one (Already availible on Modrinth, might take a while to get approved on CurseForge)

@Lemon4ik6484  hey, i had added the updated version, server starts without issues, will now seek an MooMoss  :)
